#!/usr/bin/expect

set timeout 60
set username [lindex $argv 0]
set servername [lindex $argv 1]
set password [lindex $argv 2]
set port [lindex $argv 3]

spawn ssh -p $port $username@$servername
expect {
"*(yes/no)?" {send "yes\r"; exp_continue}
"*assword:" {send "$password\r"; exp_continue}
"*\]*" {interact;}
"*\$*" {interact;}
"*\#*" {interact;}
}
exit
